### ISSUE TITLE
Save to PNG/JPEG

### ISSUE THREAD

**Issue by kontextbewusst** [AVGP/three-software-renderer#1]
Hey, thanks a lot for this great project.

Here is what I am trying: in a Hapi server application, render a very simple scene (no animation, just a single frame) to a PNG or JPEG image file and return this image in the get request.

I have fiddled for hours with pixel-utils, jpeg-js, save-pixels and mostly every image library that currently works, but the created image files are obviously malformed and cannot be viewed. It seems that I have to convert the Uint8ClampedArray somehow, but I am clueless how to do that.

Could you provide some assistance here? Thank you so much!

**Comment by AVGP** [comment]
Hey, thanks for reaching out to me - interesting question!

I don't know if you've tried it yet, but I'd use `node-png` for this:

`npm i -S node-png` and then do this:

``` javascript

/* setup your renderer, scene and all the things you need to render */

// render into pixels-array (RGBA)
var pixels = r.render(scene, cam)

var fs = require('fs'),
    PNG = require('node-png').PNG

// create a PNG to match the data
var png = new PNG({
    width: pixels.width,
    height: pixels.height,
    filterType: -1
})

// fill the data buffer for the PNG file
for(var i=0; i<pixels.data.length; i+=4) {
  png.data[i  ] = pixels.data[i  ]
  png.data[i+1] = pixels.data[i+1]
  png.data[i+2] = pixels.data[i+2]
  png.data[i+3] = 0xff
}

// parse and write to file
png.pack().pipe(fs.createWriteStream(__dirname + '/frame.png'));
```

This produces a nice PNG for the scenarios I tried.
If there's any other roadblocks, please let me know!

**Comment by AVGP** [comment]
Feel free to comment if the script in my last comment doesn't work, I'm happy to help :)

**Comment by kontextbewusst** [comment]
@AVGP this works fabulously well. Thanks a lot and sorry for my late response, I was swamped with other projects in the meantime.

**Comment by AVGP** [comment]
I am glad to hear that - and no worries, we're all busy :-)

Have fun and a great day!
