### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by jonaskello** [AVGP/three-software-renderer#4]
We have need of rendering THREEE on the server-side. So I just did the same thing as this package. Copied the SoftwareRenderer. js from THREE and rewrote to commonjs and removed dependency on canvas. Then when I was deciding the package name for publishing to npm, I discovered that the name I came up with was taken by this package :-). Very nice to find someone else who have this need as it does not seem that common.

I would very much like to collaborate on this package instead of publish what I have done. But unfortunately the project I need it for is on a tight deadline. So what I wanted to check is if I make some PRs to this repo how fast would you be able to review and merge them?

**Comment by jonaskello** [comment]
Here are some of the changes I would like to make:
1. Add three as dependency in package.json (it is a umd module now so that should work)
2. Add an example
3. Update README with a usage example
4. Synchronize changes from the SoftwareRenderer.js file in the THREE repo.
5. Add some tests (if time permits)

**Comment by AVGP** [comment]
Hey Jonas,

that's great!
I would be able to review and merge within a day, I guess.

Alternatively, as I may not always be as quick and you seem to have gone
through as much of this as I have, I'd be okay with making you a
maintainer!

Cheers,
Martin

Am 17.11.2016 10:53 vorm. schrieb "Jonas Kello" notifications@github.com:

**Comment by jonaskello** [comment]
Nice! I'll close this and start making a first PR to add an example to render to a PNG. Maybe we'll start with that first PR and then once it is merged, if you still think it is a good idea you can give me the ability to push more changes directly :-).
